### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by contentkraft**

### CODE REVIEW

**Comment by Perlkonig** [comment]
Thanks!

**Comment by Perlkonig** [comment]
Oh, I don't see a Blog plugin in the list of plugins. Where can I learn more about the plugin you reference?

**Comment by contentkraft** [comment]
It's called Bloginjector. Check it out [here](https://github.com/giansi/grav-plugin-blog).

**Comment by Perlkonig** [comment]
Thanks.

**Pull request merged**
